name = "g2fs-serverless"
compatibility_flags = ["nodejs_compat"]
main = "index.js"
compatibility_date = "2026-09-09"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true
